DROP TRIGGER SET_USER_ROLE;

--#SET TERMINATOR @
CREATE TRIGGER SET_USER_ROLE
BEFORE INSERT OR UPDATE
    ON USERS
    REFERENCING NEW AS N
 FOR EACH ROW
BEGIN
    IF N.ROLE_ID = 3 THEN
        SET N.ROLE_ID = CASE WHEN N.EMAIL LIKE 'mi_____@alas.matf.bg.ac.rs' AND N.USERNAME LIKE 'mi_____' THEN 3 ELSE 4 END;
    END IF;
END@
