CONNECT TO GRADER;

--#SET TERMINATOR @
CREATE OR REPLACE TRIGGER SET_USER_ROLE
BEFORE INSERT OR UPDATE
    ON USER
    REFERENCING NEW AS N
FOR EACH ROW
BEGIN
    SET N.ROLE_ID = CASE
        WHEN N.EMAIL LIKE 'mi_____@alas.matf.bg.ac.rs' AND N.USERNAME LIKE 'mi_____' AND N.USERNAME = SUBSTR(N.EMAIL, 1, 7) AND LENGTH(EMAIL)>LENGTH(USERNAME) THEN 3
        WHEN N.EMAIL LIKE 'mr_____@alas.matf.bg.ac.rs' AND N.USERNAME LIKE 'mr_____' AND N.USERNAME = SUBSTR(N.EMAIL, 1, 7) AND LENGTH(EMAIL)>LENGTH(USERNAME) THEN 3
        WHEN N.EMAIL LIKE '%@poincare.matf.bg.ac.rs' AND LENGTH(EMAIL)>LENGTH(USERNAME) AND SUBSTR(N.EMAIL, 1, LENGTH(N.USERNAME)) = USERNAME THEN 2
        ELSE 4 END;
END@
